[package]
name = "hoshinadev/ragdoll-tools"
description = "Server-side R6/R15 ragdoll module for Roblox projects."
version = "0.1.2"
license = "MIT"
authors = ["HoshinaDev"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"

[dependencies]